# Generated by Django 3.1.6 on 2021-02-23 13:41

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Empresa')),
                ('time_stamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_model_name', models.CharField(max_length=155, verbose_name='Nome modelo da base')),
                ('extension', models.CharField(default='', max_length=10, verbose_name='Extensão do arquivo')),
                ('importer_name', models.CharField(max_length=155, verbose_name='Nome do importer')),
                ('name_exported', models.CharField(max_length=155, verbose_name='Nome de exportação do arquivo')),
                ('log_error', models.CharField(max_length=155, verbose_name='Nome do log de erro')),
                ('log_success', models.CharField(max_length=155, verbose_name='Nome do log de sucesso')),
                ('prerequisite', models.TextField(default='Null', max_length=255, verbose_name='Pré requisito para processamento')),
                ('file_model_date', models.CharField(choices=[('%d-%m-%Y', 'DD-MM-YYYY'), ('%d-%m-%y', 'DD-MM-YY'), ('%Y-%m-%d', 'YYYY-MM-DD'), ('%y-%m-%d', 'YY-MM-DD'), ('%Y%m%d', 'YYYYMMDD'), ('%y%m%d', 'YYMMDD'), ('%d%m%Y', 'DDMMYYYY'), ('%d%m%y', 'DDMMYY')], default=[], max_length=30, verbose_name='Modelo de data arquivo')),
                ('project_directory', models.CharField(max_length=255, verbose_name='Diretório da automação')),
                ('days_of_week', multiselectfield.db.fields.MultiSelectField(choices=[('monday', 'Seg'), ('tuesday', 'Ter'), ('wednesday', 'Qua'), ('thursday', 'Qui'), ('friday', 'Sex'), ('saturday', 'Sab'), ('sunday', 'Dom')], default=[], max_length=80, verbose_name='Escolha os dias da semana para processar')),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config_file.company', verbose_name='Nome empresa')),
            ],
            options={
                'verbose_name': 'Configuração do arquivo',
                'verbose_name_plural': 'Configuração dos arquivos',
            },
        ),
        migrations.CreateModel(
            name='Historic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=155, verbose_name='Nome do arquivo')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='Tamanho')),
                ('entry_date', models.DateTimeField(verbose_name='Data de entrada')),
                ('extension', models.CharField(max_length=10, verbose_name='Extensão')),
                ('status', models.CharField(max_length=155, verbose_name='Status do arquivo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config_file.company', verbose_name='Empresa')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config_file.file', verbose_name='Arquivo')),
            ],
            options={
                'verbose_name': 'Histórico',
                'verbose_name_plural': 'Histórico dos arquivos',
            },
        ),
    ]
